version: '3.8'

services:

  db:
    image: postgres:15-alpine
    container_name: delivery_postgres
    environment:
      POSTGRES_DB: DeliveryApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d DeliveryApp"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build: .
    container_name: delivery_app
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:

      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/DeliveryApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345